/* Generated By:JavaCC: Do not edit this line. FoxtranConstants.java */
package hmm.mathias.compiler;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface FoxtranConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int PROGRAM = 6;
  /** RegularExpression Id. */
  int DEFINE = 7;
  /** RegularExpression Id. */
  int NOT = 8;
  /** RegularExpression Id. */
  int VARIABLE = 9;
  /** RegularExpression Id. */
  int IS = 10;
  /** RegularExpression Id. */
  int NATURAL = 11;
  /** RegularExpression Id. */
  int REAL = 12;
  /** RegularExpression Id. */
  int CHAR = 13;
  /** RegularExpression Id. */
  int BOOLEAN = 14;
  /** RegularExpression Id. */
  int EXECUTE = 15;
  /** RegularExpression Id. */
  int GET = 16;
  /** RegularExpression Id. */
  int PUT = 17;
  /** RegularExpression Id. */
  int LOOP = 18;
  /** RegularExpression Id. */
  int WHILE = 19;
  /** RegularExpression Id. */
  int DO = 20;
  /** RegularExpression Id. */
  int TO = 21;
  /** RegularExpression Id. */
  int SET = 22;
  /** RegularExpression Id. */
  int VERIFY = 23;
  /** RegularExpression Id. */
  int TRUE = 24;
  /** RegularExpression Id. */
  int FALSE = 25;
  /** RegularExpression Id. */
  int LPAREN = 26;
  /** RegularExpression Id. */
  int RPAREN = 27;
  /** RegularExpression Id. */
  int LCOL = 28;
  /** RegularExpression Id. */
  int RCOL = 29;
  /** RegularExpression Id. */
  int LCHAVE = 30;
  /** RegularExpression Id. */
  int RCHAVE = 31;
  /** RegularExpression Id. */
  int PONTOVIRGULA = 32;
  /** RegularExpression Id. */
  int VIRGULA = 33;
  /** RegularExpression Id. */
  int PONTO = 34;
  /** RegularExpression Id. */
  int MENORIGUAL = 35;
  /** RegularExpression Id. */
  int EXCLAMACAO = 36;
  /** RegularExpression Id. */
  int MAIS = 37;
  /** RegularExpression Id. */
  int MENOS = 38;
  /** RegularExpression Id. */
  int ASTERISCO = 39;
  /** RegularExpression Id. */
  int MAIORIGUAL = 40;
  /** RegularExpression Id. */
  int BARRA = 41;
  /** RegularExpression Id. */
  int POTENCIA = 42;
  /** RegularExpression Id. */
  int DIVISAOINTEIRA = 43;
  /** RegularExpression Id. */
  int RESTODIVISAO = 44;
  /** RegularExpression Id. */
  int LOGICOE = 45;
  /** RegularExpression Id. */
  int LOGICOOU = 46;
  /** RegularExpression Id. */
  int IGUALDADE = 47;
  /** RegularExpression Id. */
  int DIFERENCA = 48;
  /** RegularExpression Id. */
  int MAIORQUE = 49;
  /** RegularExpression Id. */
  int MENORQUE = 50;
  /** RegularExpression Id. */
  int DOGSBOLLOCKS = 51;
  /** RegularExpression Id. */
  int IDENTIFICADOR = 52;
  /** RegularExpression Id. */
  int INTEIROS = 53;
  /** RegularExpression Id. */
  int FLUTUANTES = 54;
  /** RegularExpression Id. */
  int LITERAL = 55;
  /** RegularExpression Id. */
  int LETRA = 56;
  /** RegularExpression Id. */
  int DIGITO = 57;
  /** RegularExpression Id. */
  int LINEBREAK = 58;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\n\\r\"",
    "\"\\t\"",
    "\"\\f\"",
    "\"program\"",
    "\"define\"",
    "\"not\"",
    "\"variable\"",
    "\"is\"",
    "\"natural\"",
    "\"real\"",
    "\"char\"",
    "\"boolean\"",
    "\"execute\"",
    "\"get\"",
    "\"put\"",
    "\"loop\"",
    "\"while\"",
    "\"do\"",
    "\"to\"",
    "\"set\"",
    "\"verify\"",
    "\"true\"",
    "\"false\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\"<=\"",
    "\"!\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\">=\"",
    "\"/\"",
    "\"**\"",
    "\"%\"",
    "\"%$\"",
    "\"&\"",
    "\"|\"",
    "\"==\"",
    "\"!=\"",
    "\">\"",
    "\"<\"",
    "\":-\"",
    "<IDENTIFICADOR>",
    "<INTEIROS>",
    "<FLUTUANTES>",
    "<LITERAL>",
    "<LETRA>",
    "<DIGITO>",
    "\"\\n\"",
  };

}
