/* Generated By:JavaCC: Do not edit this line. FoxtranConstants.java */
package hmm.mathias.compiler;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface FoxtranConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int PROGRAM = 7;
  /** RegularExpression Id. */
  int DEFINE = 8;
  /** RegularExpression Id. */
  int NOT = 9;
  /** RegularExpression Id. */
  int VARIABLE = 10;
  /** RegularExpression Id. */
  int IS = 11;
  /** RegularExpression Id. */
  int NATURAL = 12;
  /** RegularExpression Id. */
  int REAL = 13;
  /** RegularExpression Id. */
  int CHAR = 14;
  /** RegularExpression Id. */
  int BOOLEAN = 15;
  /** RegularExpression Id. */
  int EXECUTE = 16;
  /** RegularExpression Id. */
  int GET = 17;
  /** RegularExpression Id. */
  int PUT = 18;
  /** RegularExpression Id. */
  int LOOP = 19;
  /** RegularExpression Id. */
  int WHILE = 20;
  /** RegularExpression Id. */
  int DO = 21;
  /** RegularExpression Id. */
  int TO = 22;
  /** RegularExpression Id. */
  int SET = 23;
  /** RegularExpression Id. */
  int VERIFY = 24;
  /** RegularExpression Id. */
  int TRUE = 25;
  /** RegularExpression Id. */
  int FALSE = 26;
  /** RegularExpression Id. */
  int LPAREN = 27;
  /** RegularExpression Id. */
  int RPAREN = 28;
  /** RegularExpression Id. */
  int LCOL = 29;
  /** RegularExpression Id. */
  int RCOL = 30;
  /** RegularExpression Id. */
  int LCHAVE = 31;
  /** RegularExpression Id. */
  int RCHAVE = 32;
  /** RegularExpression Id. */
  int PONTOVIRGULA = 33;
  /** RegularExpression Id. */
  int VIRGULA = 34;
  /** RegularExpression Id. */
  int PONTO = 35;
  /** RegularExpression Id. */
  int MENORIGUAL = 36;
  /** RegularExpression Id. */
  int EXCLAMACAO = 37;
  /** RegularExpression Id. */
  int MAIS = 38;
  /** RegularExpression Id. */
  int MENOS = 39;
  /** RegularExpression Id. */
  int ASTERISCO = 40;
  /** RegularExpression Id. */
  int MAIORIGUAL = 41;
  /** RegularExpression Id. */
  int BARRA = 42;
  /** RegularExpression Id. */
  int POTENCIA = 43;
  /** RegularExpression Id. */
  int DIVISAOINTEIRA = 44;
  /** RegularExpression Id. */
  int RESTODIVISAO = 45;
  /** RegularExpression Id. */
  int LOGICOE = 46;
  /** RegularExpression Id. */
  int LOGICOOU = 47;
  /** RegularExpression Id. */
  int IGUALDADE = 48;
  /** RegularExpression Id. */
  int DIFERENCA = 49;
  /** RegularExpression Id. */
  int MAIORQUE = 50;
  /** RegularExpression Id. */
  int MENORQUE = 51;
  /** RegularExpression Id. */
  int DOGSBOLLOCKS = 52;
  /** RegularExpression Id. */
  int IDENTIFICADOR = 53;
  /** RegularExpression Id. */
  int INTEIROS = 54;
  /** RegularExpression Id. */
  int FLUTUANTE = 55;
  /** RegularExpression Id. */
  int LITERAL = 56;
  /** RegularExpression Id. */
  int LETRA = 57;
  /** RegularExpression Id. */
  int DIGITO = 58;
  /** RegularExpression Id. */
  int COMENTARIO_EM_LINHA = 59;
  /** RegularExpression Id. */
  int COMENTARIO_EM_MULTILINHA = 60;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\n\\r\"",
    "\"\\t\"",
    "\"\\f\"",
    "\"program\"",
    "\"define\"",
    "\"not\"",
    "\"variable\"",
    "\"is\"",
    "\"natural\"",
    "\"real\"",
    "\"char\"",
    "\"boolean\"",
    "\"execute\"",
    "\"get\"",
    "\"put\"",
    "\"loop\"",
    "\"while\"",
    "\"do\"",
    "\"to\"",
    "\"set\"",
    "\"verify\"",
    "\"true\"",
    "\"false\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\"<=\"",
    "\"!\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\">=\"",
    "\"/\"",
    "\"**\"",
    "\"%\"",
    "\"%%\"",
    "\"&\"",
    "\"|\"",
    "\"==\"",
    "\"!=\"",
    "\">\"",
    "\"<\"",
    "\":-\"",
    "<IDENTIFICADOR>",
    "<INTEIROS>",
    "<FLUTUANTE>",
    "<LITERAL>",
    "<LETRA>",
    "<DIGITO>",
    "<COMENTARIO_EM_LINHA>",
    "<COMENTARIO_EM_MULTILINHA>",
  };

}
